### ISSUE TITLE
Heroku Scheduler

### ISSUE THREAD

**Issue by catanach** [LandonPatmore/yahoo-fantasy-bot#82]
Love the bot, thanks for all your work on this!

In order to stay in the free tier of Heroku, I'm trying to get this run on a schedule, instead of 24/7. Is there a known method for doing this easily?

**Comment by LandonPatmore** [comment]
I personally don't know how to do that since I have never explored that option. I have just added my credit card to my account and it bumps the 500 hours limit to 1000 hours. Since there are ~730 hours in a month (based on days), it covers that. I have never been charged since adding it 3 years ago. You can explore that option. Otherwise, I would recommend taking a look at their documentation: https://devcenter.heroku.com/categories/reference

**Comment by catanach** [comment]
Thanks for your response. I did realize after adding this ticket that adding CC info would give me enough time.
